export const FACULTY = [
  "Dr. Ramaraju",
  "Dr. Shivashankara",
  "Dr. Neethu",
  "Dr. Manjunatha",
  "Dr. Prashant",
  "Dr. Shanthi",
  "Dr. Sowmya",
  "Dr. Shiva",
  "Dr. Venkatesha",
  "Dr. Gokulan",
  "Dr. Mayank",
  "Mrs. Meghashree",
  "Dr. Vinay",
  "Mr. Sanjeev",
  "Mrs. Tahera",
  "Mr. Shahaji",
  "Mr. Nitin",
  "Dr. Sudeep",
  "Prof. Spoorthy",
  "Prof. Sridhar",
  "Prof. Ashwini",
  "Prof. Nagamani",
  "Prof. Raghavendra H.N.",
  "Dr. Geetha",
  "Mr. Ujwal",
  "Dr. Ravindranath",
  "Dr. Sathvik",
  "Prof. Raghavendra Prajwal",
  "Prof. Harshitha",
  "Prof. Vidyashree",
  "Dr. Karthik S",
  "Dr. Sumesh",
  "Dr. Christo",
  "Dr. Karthik M",
  "Dr. Gautam",
  "Mrs. Swetti",
  "Prof. Vibhashree",
  "Prof. Raghavendra Mahesh",
  "Prof. Madhura",
  "Prof. Sankalp",
  "Prof. Thanushree",
  "Dr. Doma",
  "Dr. Pujitha"
] as const;

export const QUESTIONS = [
  "Always has a smile on their face",
  "Loudest laugh in the staff room",
  "Biggest yapper",
  "Best storyteller",
  "Most likely to give a 10-minute answer to a yes/no question",
  "Most likely to get distracted mid-sentence and forget what they were saying",
  "Best at sneaking in a power nap",
  "Most likely to forget where they kept their phone or keys",
  "Most organized desk or bag",
  "Best handwriting on the whiteboard",
  "Fastest walker in the corridor",
  "Slowest walker in the corridor",
  "Seems to be everywhere at once",
  "Most likely to keep teaching even after the bell rings",
  "Brings the best energy on Monday mornings",
  "Most energetic faculty member",
  "Most likely to win a dance-off",
  "Takes the lead most often",
  "Most laid-back faculty member",
  "Strictest faculty member",
  "Has a hidden talent nobody knows about",
  "Most likely to become a stand-up comedian if teaching did not work out",
  "Most likely to survive a zombie apocalypse using just classroom supplies",
  "Trendiest dresser",
  "Most likely to be mistaken for a student",
  "Biggest gym enthusiast",
  "Healthiest lifestyle",
  "Biggest foodie",
  "Tallest faculty member",
  "Most active on social media",
  "Most likely to still be answering emails at 11 PM",
  "Never takes a leave",
  "Most likely to still be at school after everyone has left",
  "First one to arrive every day",
  "Best at multitasking",
  "Most multi-talented faculty member",
  "Most likely to have snacks in their bag or drawer",
  "Best faculty duo",
  "Most likely to remember everyone's birthday",
  "Biggest cheerleader for students",
  "Most likely to remember a student from 10 years ago"
] as const;

export const DUO_QUESTION_INDEX = 37;
export const TOTAL_QUESTIONS = QUESTIONS.length;

export type FacultyName = typeof FACULTY[number];
